### ISSUE TITLE
Offline Installation Font Rendering: Text boxes too small

### ISSUE THREAD

**Issue by flaxsh** [Jineapple/WololoKingdoms#45]
Text in the offline installation seems to use a font that is too tall for the text boxes.
In dropdown menus this makes all entries except one disappear
![dropdownoneentry](https://user-images.githubusercontent.com/15833628/43584418-9d745768-9662-11e8-8d2c-76b9d0dc8196.PNG)

![textboxtoosmall](https://user-images.githubusercontent.com/15833628/43584310-59d1796e-9662-11e8-8e33-ed4aa3ca8a47.PNG)

**Comment by Jineapple** [comment]
This happens due to bugged Language dlls that come with the compatibility patch. To fix, do the following:
1. Download the aoc language file here: https://www.aoezone.net/threads/aoc-language-files.32232/
2. Replace the files in your aoc installation (Usually in the /Age2HD folder)
3. Run the installer again.
